version: "3"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"   # port Vite.js
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
